// Generated by CoffeeScript 1.8.0
var defaults;

require("shelljs/global");

defaults = {
  nuget_exe: "tools/nuget/NuGet.exe",
  task: "restore",
  args: "src/AirPlans.sln"
};

module.exports = function(grunt) {
  grunt.registerTask("nuget", "Nuget command line implementation", function() {
    var monoPrefix, options, _ref;
    options = this.options(defaults);
    monoPrefix = (_ref = process.platform) === "linux" || _ref === "darwin" ? "mono " : "";
    exec("" + monoPrefix + " " + options.nuget_exe + " " + options.task + " " + options.args);
  });
};

//# sourceMappingURL=index.js.map
